security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'bcrypt'
    providers:
        app_email_provider:
            entity:
                class: App\Entity\User
                property: email
        app_id_provider:
            entity:
                class: App\Entity\User
                property: id
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        api:
            access_token:
                token_handler: App\Security\AccessTokenHandler
            pattern: ^/api
            provider: app_id_provider
        main:
            json_login:
                check_path: app_login
            provider: app_email_provider
            user_checker: App\Security\InactiveUserChecker

    access_control:
        - { path: ^/api/admin, roles: ROLE_ADMIN }
        - { path: ^/api/teacher, roles: ROLE_TEACHER }
        - { path: ^/api/public, roles: PUBLIC_ACCESS }
        - { path: ^/api, roles: ROLE_USER }
        - { path: ^/, roles: IS_AUTHENTICATED_FULLY}

when@test:
    security:
        password_hashers:
            Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface:
                algorithm: auto
                cost: 4
                time_cost: 3
                memory_cost: 10
